# Generated by Django 5.1.6 on 2025-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('money_value', models.IntegerField(default=100)),
                ('achived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='media/images/')),
                ('gold', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReglCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regl_date', models.DateField()),
                ('ovulation_date', models.DateField()),
                ('expected_regl_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('achived', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('code', models.CharField(max_length=50)),
            ],
        ),
    ]
